import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]
[font]
size = 14.0

[font.bold]
family = "Roboto Mono"
style = "Bold"

[font.bold_italic]
family = "Roboto Mono"
style = "Bold Italic"

[font.italic]
family = "Roboto Mono"
style = "Italic"

[font.normal]
family = "Roboto Mono"
style = "Regular"

[env]
term = "xterm-256color"

[window.dimensions]
columns = 200
lines = 60

[window.padding]
x = 5
y = 5
